url:
  en: https://thematiaz0.github.io
  pl: https://thematiaz0.github.io/pl

description:
  en: Game Developer, C# Programmer and Designer Portfolio of Mateusz Kusionowicz. 3 years of experience in Unity, C#, Gameplay Programming, UI Programming.
  pl: Twórca gier, programista C# - portfolio Mateusz Kusionowicz. 3 lata doświadczenia w Unity, C#, programowanie rozgrywki i programowanie UI.

keywords:
  en: game games video development programming software engineer engineering entertainment developer c# unity ui design designer portfolio 2D Poland Polska remote freelance work unity3d Cracow employee Mateusz Kusionowicz TheMatiaz0
  pl: gra gry wideo tworzenie programowanie program programista developer designer rozrywka c# unity ui zlecenie freelance portfolio design 2D unity3d Poland Polska zdalne Kraków praca pracownik Mateusz Kusionowicz TheMatiaz0